language: python
dist: xenial
python:
  - pypy
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install tox-travis
script:
  - tox
after_success:
  - test "${TRAVIS_TAG}" != "" && docs/deploy.sh
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jfinkhaeuser
  password:
    secure: f3CKGqBC9mDEYQUrlN9BCP0FtToJsx7I+Jf5VrB6rVhFWmrpKnZFc5dBgnlLtzJ245ctjj4AI5knbjC88VjgcfXdp5kM1PeOIHhsLHe/5yvajhuo5IBtH8hclOSuDnciVyIrhTzUM2TyZjTqpWfFHMJgZ5MNzJt27jC00yktLlHNtFTUPQoQTrjptu9hEwqLJO4bfgjKHdJEaxLEHAfJ0Kungti2AnS5HlhLKzc9bB/5nKvRCwFdPwPbr2IzIkw/EXy1ONObPpQAedyEk0ViV9LPxke0uvqPAkeyXnUrrrRJ1gYR7oRyETsmhWg25A/x+X4v9g0b35U0LUI5uooizHjii9Q0SWBzQ/sqmG12HC1tsmkRt7JcTSba2PgtGYxPzcPoYxkCHbxem0kboQH2Awz81qbAm6RNemkbKEWm90bvVqGfCnf5xv9C98yY6+PjxRe60R7doLz8K69y4QNMd+lCkvmtT5e537rDGBwQUfJsBOOMFECuzObjXg4RwCaRMZKG0k/EXaApPYwOJVZA56IjU0+dIUeoZN/ehPW+qMt2XwKRsVZSb9kEQP5i4Sq7VkNnGrHxmKj6VJX93TsbBK2k68IhBYwxncGOa+kaTP5+irXTWYnf3qs/fu/G8qTJSF+kTwBbw3JiNyIFGu2PQ40CLwz6Ebrz3eYGOb5JgFI=
  on:
    tags: true
    branch: master
    repo: jfinkhaeuser/prance
    condition: "$(python --version | grep '^Python 3\\.6')"
env:
  global:
    - secure: OBNymO/NhhWmcI/Vqs4TcxYCSPoDAblnurdjC11h0xi0OVNfddhKEIlcump3G7vZZNJucepp2SOVV8rrUE1ATbxQnZzMwAarfW61l4aoAXP1y4oZkVrDVMdXTKMU2t1iXpjU7rQSCnJ9GhLyyC8I5EJTeJR9nwhts2sh186QyJM3rnjdt8C6PULh48YvpU9sKoazShzqL0s+L8wHQeh1BTRu7DMFQwmZl+dFc1RSO/Q3hpVIBk/9cdlCixWQZzPu14Z0gjX76qsVixKJ1oB+2wVIiMDwMS1h7HGQhJTY3B47orAkiSK8EbmPBBKzqD0oNEq9e98x7V/+Hre7Hw4EoMLZHeBcyeQ998T7XbYpR1/19nVyXb8epZ6q6Uo7q5+GWUr+cDdY+d/AzGed4uOh7YD+mqn+BVg+h5JyGabRpfIAeeCbwQ5Uq9WSdVhcyDeqAwSsC2uGuMSuZaTgs0aU3uXOgZpmCPA35Qs0qVOFldeId7FU+JW+ij98/B+dgTqB7ZXCFsG+BTmYxnE3Iza6dtJoe5NEYadEXiPMZG3BBcra9UN77ltmmsfentujhkgcof1H+1o85nTY2ry6SkTICmibt7egJbiKb1jr0yn0FqBvzUKJCTqIN3gQFWeC2A2FQej2EvxMcx/QRmFPK6ylVQJjbZHsoGJs/yf9fuLlyBg=
    - CC=gcc-8
    - CXX=g++-8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    update: true
    packages:
      - g++-8
      - libicu-dev
